### ISSUE TITLE
Setting siteId in project config is broken

### ISSUE THREAD

**Issue by boboldehampsink** [studioespresso/craft-google-shopping-feed#10]
It still uses the `id` instead of the `uid`, which only works if the id on the dev site for example is the same as on the prod site.

**Comment by janhenckens** [comment]
Hey @boboldehampsink, when are you running into an issue with this? 
The `siteId` setting is not exposed in settings so I assume you're configuring the plugin through a config file?

**Comment by boboldehampsink** [comment]
What do you mean, it is not exposed in the settings? This is a screenshot of the settings with the site setting:

<img width="393" alt="Screen Shot 2021-02-15 at 07 43 49" src="https://user-images.githubusercontent.com/378974/107913946-aecb4500-6f61-11eb-868c-ada8e2cba132.png">

And the plugin settings are being saved into project.yaml like this (see siteId being present)

<img width="224" alt="Screen Shot 2021-02-15 at 07 44 09" src="https://user-images.githubusercontent.com/378974/107913965-bc80ca80-6f61-11eb-8a55-1e5b94845041.png">

**Comment by janhenckens** [comment]
Damn, i must not have been fully awake 🙃. And I had to nuke my test install last week so I only had one site.
I'll get right on fixing this!

**Comment by janhenckens** [comment]
Fixed in 1.3.0!
