### ISSUE TITLE
How is the plugin working?

### ISSUE THREAD

**Issue by DigitalGrafix** [studioespresso/craft-google-shopping-feed#12]
Hi,
i just bought the plugin and now want to run the default feed. So i did the setting and then hit the feed url under: 
website.com/feeds/products/google and then i got a 404 error. What am i doing wrong? Do i have to manually set up some templates in that path?
Thanks for an answer!

**Comment by janhenckens** [comment]
Hey @DigitalGrafix, have you tried saving the plugin settings and then viewing the feed?

I would also strongly recommend first **trying** a plugin to see if it works for what you want to use it before buying it :)

**Comment by DigitalGrafix** [comment]
Thanks for the quick answer. Yes i saved the settings. So i did nothing wrong with the plugin? Install - Setting - FeedUrl in Browser.  No problem with the money - i wondered if this was a problem so i bought it :).

**Comment by janhenckens** [comment]
Could you post a printscreen your settings and of the 404?

**Comment by DigitalGrafix** [comment]
<img width="1531" alt="Bildschirmfoto 2021-03-11 um 14 03 56" src="https://user-images.githubusercontent.com/80463170/110791586-ad482080-8272-11eb-9989-a9819c39a956.png">
<img width="1150" alt="Bildschirmfoto 2021-03-11 um 14 03 42" src="https://user-images.githubusercontent.com/80463170/110791615-b33e0180-8272-11eb-9e28-0acf651856cc.png">

**Comment by DigitalGrafix** [comment]
I have an update. The 404 Error was from my Redirect Plugin - now i got this error:
Argument 1 passed to craft\services\Sites::getSiteById() must be of the type int, null given, called in /usr/www/users/xxx/xxx/vendor/studioespresso/craft-google-shopping-feed/src/services/ElementsService.php on line 30

**Comment by bernsno** [comment]
We're also experiencing this error ^

**Comment by janhenckens** [comment]
Hey all, this should be fixed in the update I released today (1.3.1). Do get in touch if you run into any other issues!
