### ISSUE TITLE
Internal server error in 3.0.34

### ISSUE THREAD

**Issue by DXMDan** [studioespresso/craft-google-shopping-feed#3]
Getting the internal server error 
"error on line 41 at column 43: EntityRef: expecting ';'" 
After install of plugin and navigating to "/feeds/products/google"

Craft CMS 3.0.34

**Comment by janhenckens** [comment]
Hey Dann
Thanks for reporting this, I'll have a look tonight!

**Comment by janhenckens** [comment]
Hey Dann

Could you post the full exception and some more information? Are you using the plugin with Craft commerce or with regular entries?

**Comment by DXMDan** [comment]
`This page contains the following errors:
error on line 41 at column 43: EntityRef: expecting ';'
Below is a rendering of the page up to the first error.`

This is the full output we are getting on the error.
We are using Craft Commerce 2.0.0-beta.12.1

**Comment by DXMDan** [comment]
Issue resolved in 1.1.0
