### ISSUE TITLE
Default option for feed fields

### ISSUE THREAD

**Issue by stenvdb** [studioespresso/craft-google-shopping-feed#4]
For example, when using this plugin in a shop for a specific brand, then there will not be a brand field. Allowing a default option in the plugin settings if a certain field is missing would be handy.

There is also a small typo in the settings template, the label for the price input field is marked as "Product id".

**Comment by janhenckens** [comment]
Hey Sten,
Good idea! I'm halfway through a similar feature for my Facebook Product Feed plugin but it's equally relevant here. I'll move it up the list 🙂

**Comment by janhenckens** [comment]
Hey Sten, just released an update that includes this. Can you give it a try? Let me know if there's anything else you'd like to see added :)

**Comment by stenvdb** [comment]
Worked like a charm!

Bedankt Jan 😉
