### ISSUE TITLE
Custom Twig can't get related entry fields

### ISSUE THREAD

**Issue by chadcrowell** [studioespresso/craft-google-shopping-feed#5]
I have products that are based on entries... each product has a field called "sourceProduct" that is an Entries relationship field where the related entry contains the product description, images, etc. that are shown on the product detail page in the store. So, in the feed I need to do something along these lines:

```
{{ craft.googleshopping.products(query, {
                title: 'title',
                id: 'sku',
                description: 'sourceProduct.description',
                image_link: 'sourceProduct.productImages.one().url()',
                brand: 'GCX',
                price: 'defaultPrice',
                currency: 'USD'
           }) }}
```

but those field names aren't being parsed by the plugin. Is there any way to get these to work? Here is my entire custom twig feed code:

```
{% set query = craft.products.limit(10) %}

<?xml version="1.0" encoding="utf-8"?>
<rss version="2.0"
     xmlns:dc="http://purl.org/dc/elements/1.1/"
     xmlns:sy="http://purl.org/rss/1.0/modules/syndication/"
     xmlns:admin="http://webns.net/mvcb/"
     xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#"
     xmlns:content="http://purl.org/rss/1.0/modules/content/"
     xmlns:g="http://base.google.com/ns/1.0">
    <channel>
        <title>{{ systemName }}</title>
        <link>{{ parseEnv(currentSite.baseUrl) }}</link>

        {{ craft.googleshopping.products(query, {
                title: 'title',
                id: 'sku',
                description: 'sourceProduct.description',
                image_link: 'sourceProduct.productImages.one().url()',
                brand: 'GCX',
                price: 'defaultPrice',
                currency: 'USD'
           }) }}

    </channel>
</rss>
```

**Comment by chadcrowell** [comment]
Hi, any progress on this at all? Thanks.

**Comment by janhenckens** [comment]
Hey Chad, I don't think that's possible in the plugin right now.
I think it would be quicker if you print the XML in your twig code yourself, without the plugin.
You can have a look at the [template](https://github.com/studioespresso/craft-google-shopping-feed/blob/develop/src/templates/_entries.twig) the plugin uses to do this. 

Happy to help you out if you need a hand!
