### ISSUE TITLE
Add mpn field

### ISSUE THREAD

**Issue by mhayes14** [studioespresso/craft-google-shopping-feed#6]
Hi

My client is happy with this plugin and has a license in place but requires the [mpn](https://support.google.com/merchants/answer/6324482) field in their feed. I'm not overly familiar with Google Merchant Feeds but this seems like a field others would require. Do you think this is something you could add?

Thanks
Mike

**Comment by janhenckens** [comment]
Hey Mike

Do you have to mpn field mapped on the product in the CP? Then I can add an option to the settings to link it up.

**Comment by mhayes14** [comment]
Hi Jan

That's right - there's a field on the product representing the MPN so it
just needs linking up and returned in the feed.

Thanks
Mike

**Comment by janhenckens** [comment]
Hey Mike, just released an update that includes this, can you give it a try?

Thanks.

**Comment by mhayes14** [comment]
Hi Jan

Thanks for this, I am running into an issue. The field I've selected 'SKU' is resulting in an error being thrown because it doesn't exist on Products belonging to a Product Type with variants enabled (in this case each variant has its own SKU but the Product entity does have a defaultSku attribute which could be used in the feed). Any ideas how this could be catered for? As with most things, I guess this isn't as straight forward as thought originally.

Thanks!
Mike

**Comment by janhenckens** [comment]
Which version of Craft Commerce are you running?

**Comment by mhayes14** [comment]
It's Craft Commerce 2.1.13 currently.

Thanks
Mike

**Comment by janhenckens** [comment]
I'll try to reproduce with variants enabled, that's probably a good case to cover by default. I'll keep you posted!

**Comment by mhayes14** [comment]
Hi @janhenckens 

Sorry to bug you - appreciate the license fee isn't huge. My client is eager to get their feed up and running with the MPN field in place. Do you think this is something you may have a chance to sort out soon? Just so I can communicate expectations/timings with my client or consider whether it would be best for me to implement the feed (or perhaps plugin fix) instead.

Thanks!
Mike

**Comment by janhenckens** [comment]
Hey Mike, sorry about that, didn't realize you already had a license since this seems like a show-stopping issue for your project...

I'll try to get to it this week but I'm also moving appartments so I can't give you a specific timing.

**Comment by mhayes14** [comment]
No problem, thanks for the update - I will feed this back to my client. All the best with the move, I know how stressful it can be.

Thanks
Mike

**Comment by janhenckens** [comment]
Hey Mike

I tried to reproduce thise but on my end it works when I have variants enabled:
<img width="1101" alt="Screenshot 2020-03-03 at 19 10 46" src="https://user-images.githubusercontent.com/755428/75806847-b8759000-5d84-11ea-9ba6-060d8e2fa861.png">

Could you share more information about how you have products set up?

**Comment by mhayes14** [comment]
It's a fairly basic product set up. The problem is when the MPN field in the Google Shopping Feed settings is mapped to the SKU product attribute, which doesn't exist for products with variants. Did you try setting the MPN field to SKU?

There seems to have been the same issue previously where the ID field was set to the SKU, so there's an additional `if` clause [here](https://github.com/studioespresso/craft-google-shopping-feed/blob/develop/src/templates/_products.twig#L9-L11) to fetch the default variant SKU:

```
{% if settings.id == 'sku' %}
    {% set id = product.defaultVariant.sku %}
{% else %}
```

Looking at [lines 52-58 in settings.twig](https://github.com/studioespresso/craft-google-shopping-feed/blob/develop/src/templates/settings.twig#L52-L58), it seems the mapping could be changed from `sku` to `defaultSku`:

```
{% set availableFields = {
    '' : '---',
    'title' : 'Title',
    'defaultSku' : 'SKU',
    'id' : 'Entry ID',
    'price': 'Price',
} %}
```

I have tested this. It resolves my issue because all products - both those with and without variants enabled - have a `defaultSku` attribute. It also means the `if` clause on line 9 of `_products.twig` to grab `product.defaultVariant.sku` can be removed too.

Hopefully you can reproduce if the MPN field is mapped to the SKU attribute and the above fix works.

**Comment by mhayes14** [comment]
Hi Jan

My client (customer of your plugin) is asking for an update on this. I am sorry to bug you, I'm sure you're busy and appreciate it's a tough time for everybody at the moment. I'm just wondering if you had a chance to review the fix above - perhaps it would be better if I submitted a PR?

Thank you
Mike

**Comment by janhenckens** [comment]
Hey Mike
For some reason I only read the first paragraph of your previous reply and not the entire thing with the code sample 🙈. Having a look at it right away!

**Comment by janhenckens** [comment]
Added some extra code to make it work with the current SKU field, so the update doesn't break for existing installs. Can you give the latest release a try?

**Comment by mhayes14** [comment]
Hey

I've just had a chance to test and can confirm the issue is now resolved. Thanks for your help!

All the best,
Mike
